---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: goof
  name: goof
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: goof
  template:
    metadata:
      labels:
        app: goof
    spec:
      containers:
      - image: ${DOCKER_ACCOUNT}/java-goof:1.0.0  # Use a specific version tag
        imagePullPolicy: Always
        name: java-goof
        securityContext:
          capabilities:
            drop: ["ALL"]  # Drop all default capabilities
            add: ["NET_BIND_SERVICE"]  # Add only the necessary capabilities
      restartPolicy: Always  # Move this to the pod spec level
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: goof
  name: goof
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: goof
